name: simple_deployment_pipeline

on:
  push:
    branches:
      - main


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint
